# Exported from Render on 2026-02-13T18:07:04Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: monkeygg2.github.io
      runtime: node
      repo: https://github.com/FakeNewsFishatschool/monkeygg2.github.io
      plan: free
      region: oregon
      buildCommand: yarn
      startCommand: yarn start
      autoDeployTrigger: commit
